version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: "@google-cloud/firestore"
    versions:
    - 4.10.0
    - 4.9.8
    - 4.9.9
  - dependency-name: eslint
    versions:
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: natural
    versions:
    - 3.0.0
    - 3.0.1
    - 3.0.3
    - 4.0.0
    - 4.0.1
    - 4.0.2
    - 4.0.3
    - 4.0.4
    - 5.0.0
    - 5.0.1
    - 5.0.2
  - dependency-name: "@types/js-yaml"
    versions:
    - 4.0.0
  - dependency-name: js-yaml
    versions:
    - 4.0.0
  - dependency-name: typedoc
    versions:
    - 0.20.19
    - 0.20.20
    - 0.20.21
    - 0.20.22
    - 0.20.23
    - 0.20.24
    - 0.20.25
    - 0.20.26
    - 0.20.27
    - 0.20.28
    - 0.20.29
    - 0.20.30
    - 0.20.31
    - 0.20.32
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - legowerewolf
  ignore:
  - dependency-name: node
    versions:
    - 15.10.0
    - 15.12.0
    - 15.13.0
    - 15.14.0
    - 15.7.0
    - 15.8.0
    - 15.9.0
