arrowParens: always
bracketSpacing: true
endOfLine: auto
htmlWhitespaceSensitivity: css
insertPragma: false
printWidth: 240
proseWrap: always
quoteProps: as-needed
requirePragma: false
semi: true
singleQuote: false
tabWidth: 4
trailingComma: es5
useTabs: true

overrides:
  - files:
      - "*.yml"
      - "**.yaml"
    options:
      tabWidth: 2

  - files:
      - "*.md"
    options:
      printWidth: 80
