from node:latest as builder
copy . /app/
workdir /app/
run npm ci              && \
    npm run build

from node:slim
workdir /app/
copy --from=builder /app/build/ .
copy ./config ./config
cmd node bundle.js