FROM resin/%%RESIN_MACHINE_NAME%%-node as builder
COPY . .
RUN npm i && \
    npm i -g gulp-cli && \
    gulp default-nowatch

FROM resin/%%RESIN_MACHINE_NAME%%-node
ENV INITSYSTEM on
COPY --from=builder ./build ./build
COPY --from=builder ./config ./config
RUN npm i --production
CMD ["node", "build/index"]